In [1]:
import numpy as np

### Load Dataset

y = 0.3(w) * x
- 여기서 w는 weight(가중치)

In [3]:
x1 = np.random.uniform(low = -1.0, high = 1.0, size = 100)  # uniform : 유니폼 분포 : 주사위 던지기와 같다.

print(x1.shape)
x1[:10]

(100,)


array([-0.28311736, -0.74160018, -0.52008522, -0.17275746,  0.32874648,
       -0.97942075, -0.56561734,  0.86530835, -0.75511076, -0.97880444])

In [4]:
x2 = np.random.uniform(low = -1.0, high = 1.0, size = 100)  # uniform : 유니폼 분포 : 주사위 던지기와 같다.

print(x2.shape)
x2[:10]

(100,)


array([ 0.23740188,  0.61724418,  0.09793923, -0.62747287, -0.83442145,
       -0.30603561, -0.21793089,  0.00418102, -0.12495863,  0.01241239])

In [6]:
y = 0.3 * x1 + 0.5 * x2 + 0.1

print(y.shape)
y[:10]

(100,)


array([ 0.13376573,  0.18614203, -0.00705595, -0.26556368, -0.21858678,
       -0.34684403, -0.17865065,  0.36168301, -0.18901254, -0.18743514])

In [7]:
x3 = np.array([1] * 100)
x3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
y = 0.3 * x1 + 0.5 * x2 + 0.1 * x3

print(y.shape)
y[:10]

(100,)


array([ 0.13376573,  0.18614203, -0.00705595, -0.26556368, -0.21858678,
       -0.34684403, -0.17865065,  0.36168301, -0.18901254, -0.18743514])

### Random Search

In [9]:
num_epoch = 1000000

best_error = 9999
best_w1 = None
best_w2 = None
best_b = None
best_epoch = None

for epoch in range(num_epoch):
    w1 = np.random.uniform(low = -1.0, high = 1.0)
    w2 = np.random.uniform(low = -1.0, high = 1.0)
    b = np.random.uniform(low = -1.0, high = 1.0)
    
    y_predict = w1 * x1 + w2 * x2 + b
    
    error = np.abs(y_predict - y).mean()  # abs : 절대값. 
    # 절대값을 취해주지 않으면 정답이 틀렸음에도 error가 0으로 나올 수 있다.
    
    if error < best_error:  # 현재 에러가 bset_error보다 작다면
        best_error = error  # best_error를 갱신
        best_w1 = w1
        best_w2 = w2
        best_b = b
        best_epoch = epoch
        
        print(f'{best_epoch}, w1 = {best_w1:.6f}, w2 = {best_w2:.6f}, error = {best_error:.6f}')
        
print('----' * 10)
print(f'{best_epoch}, w1 = {best_w1:.6f}, w2 = {best_w2:.6f}, b = {best_b:.6f}, error = {best_error:.6f}')

0, w1 = 0.947169, w2 = -0.198042, error = 0.443890
3, w1 = 0.169181, w2 = 0.668200, error = 0.119155
193, w1 = 0.237778, w2 = 0.622929, error = 0.113436
479, w1 = 0.240194, w2 = 0.519461, error = 0.046912
13799, w1 = 0.243333, w2 = 0.427903, error = 0.043368
20504, w1 = 0.317123, w2 = 0.470289, error = 0.021771
90167, w1 = 0.293367, w2 = 0.515514, error = 0.019451
99519, w1 = 0.310011, w2 = 0.494178, error = 0.009812
660264, w1 = 0.290237, w2 = 0.504530, error = 0.005238
847630, w1 = 0.293561, w2 = 0.505577, error = 0.004372
----------------------------------------
847630, w1 = 0.293561, w2 = 0.505577, b = 0.096747, error = 0.004372


In [10]:
y_example = [-1, 0, +1]
y_predict_example = [+1, -1, 0]

y_example = np.array(y_example)
y_predict_example = np.array(y_predict_example)

np.abs(y_predict_example - y_example).mean()

1.3333333333333333

### h_step search

In [11]:
# h_step search의 장점 :
# w1이 0.3이 아닌 값. 쉽게 말해서 w1이 -1 ~ +1 사이의 값이 아닌 값이어도 찾을 수 있다.
# 단점 : h를 우리가 직접 지정해줘야한다. ==> w가 커지면 h도 커져야하고 이렇게 되면 오차가 많이 생길 수 있다.

num_epoch = 100
h = 0.05

w1 = np.random.uniform(low = -1.0, high = 1.0)

for epoch in range(num_epoch):
    y_predict = w1 * x1
    
    current_error = np.abs(y_predict - y).mean()
    
    y_predict = (w1 + h) * x1
    h_plus_error = np.abs(y_predict - y).mean()
    
    if h_plus_error < current_error:
        w1 = w1 + h
        print(f'{epoch}, w1 = {w1:.6f}, error = {h_plus_error:.6f}')
        continue  # h_plus_error가 true가 나와 작아졌을때는 continue
    
    y_predict = (w1 - h) * x1
    h_minus_error = np.abs(y_predict - y).mean()
    
    if h_minus_error < current_error:
        w1 = w1 - h
        print(f'{epoch}, w1 = {w1:.6f}, error = {h_minus_error:.6f}')
        continue
    
    break  # h_plus_error가 작지 않은 상황이면 break로 멈춰준다.
print('----' * 10)    
print(f'{epoch}, w1 = {w1:.6f}, error = {current_error:.6f}')

0, w1 = 0.944616, error = 0.406440
1, w1 = 0.894616, error = 0.387132
2, w1 = 0.844616, error = 0.368738
3, w1 = 0.794616, error = 0.351048
4, w1 = 0.744616, error = 0.334544
5, w1 = 0.694616, error = 0.318910
6, w1 = 0.644616, error = 0.305443
7, w1 = 0.594616, error = 0.293249
8, w1 = 0.544616, error = 0.282493
9, w1 = 0.494616, error = 0.272976
10, w1 = 0.444616, error = 0.264793
11, w1 = 0.394616, error = 0.258600
12, w1 = 0.344616, error = 0.255279
13, w1 = 0.294616, error = 0.254491
----------------------------------------
14, w1 = 0.294616, error = 0.254491


### Gradient Descent

In [12]:
num_epoch = 100
learning_rate = 1.0

w1 = np.random.uniform(low = -1.0, high = 1.0)
w2 = np.random.uniform(low = -1.0, high = 1.0)
b = np.random.uniform(low = -1.0, high = 1.0)

for epoch in range(num_epoch):
    y_predict = w1 * x1 + w2 * x2 + b
    
    error = np.abs(y_predict - y).mean()
    
    if error < 0.0005:
        break
    
    print(f'{epoch}, w1 = {w1:.6f}, w2 = {w2:.6f}, b = {b:.6f}, error = {error:.6f}')
    
    w1 = w1 - learning_rate * ((y_predict - y) * x1).mean()  # w1은 하나이고 y_predict와 y는 100개이기 때문에 사이즈가 맞기 않아 평균값을 낸다.
    w2 = w2 - learning_rate * ((y_predict - y) * x2).mean()
    b = b - learning_rate * (y_predict - y).mean()  # * x3해줘야 하지만 x3=1이기 때문에 생략
    
print('----' * 10)    
print(f'{epoch}, w1 = {w1:.6f}, w2 = {w2:.6f}, b = {b:.6f}, error = {error:.6f}')

0, w1 = -0.083053, w2 = 0.381911, b = 0.527560, error = 0.438968
1, w1 = 0.064717, w2 = 0.382431, b = 0.089166, error = 0.126987
2, w1 = 0.141490, w2 = 0.414179, b = 0.096365, error = 0.086390
3, w1 = 0.193303, w2 = 0.437246, b = 0.097995, error = 0.058954
4, w1 = 0.228134, w2 = 0.454193, b = 0.098984, error = 0.040316
5, w1 = 0.251563, w2 = 0.466614, b = 0.099553, error = 0.027629
6, w1 = 0.267332, w2 = 0.475700, b = 0.099867, error = 0.019012
7, w1 = 0.277952, w2 = 0.482336, b = 0.100030, error = 0.013116
8, w1 = 0.285108, w2 = 0.487173, b = 0.100105, error = 0.009071
9, w1 = 0.289933, w2 = 0.490696, b = 0.100131, error = 0.006283
10, w1 = 0.293190, w2 = 0.493257, b = 0.100131, error = 0.004369
11, w1 = 0.295389, w2 = 0.495117, b = 0.100119, error = 0.003061
12, w1 = 0.296875, w2 = 0.496467, b = 0.100102, error = 0.002149
13, w1 = 0.297880, w2 = 0.497445, b = 0.100084, error = 0.001510
14, w1 = 0.298561, w2 = 0.498154, b = 0.100068, error = 0.001064
15, w1 = 0.299022, w2 = 0.498667, 