In [2]:
a = 5
a

5

In [3]:
type(a)

int

In [4]:
b = 7.5
b

7.5

In [5]:
type(b)

float

In [6]:
a + b

12.5

In [7]:
b - a

2.5

In [8]:
a - b

-2.5

In [9]:
a * b

37.5

In [10]:
a / b

0.6666666666666666

In [11]:
a % b

5.0

In [12]:
import numpy as np

In [15]:
x = np.array([1, 2, 3])
y = np.array([3, 6, 9])

In [17]:
x

array([1, 2, 3])

In [18]:
y

array([3, 6, 9])

In [19]:
# element_wise operation
x + y

array([ 4,  8, 12])

In [21]:
x - y

array([-2, -4, -6])

In [22]:
x * y

array([ 3, 12, 27])

In [23]:
x / y

array([0.33333333, 0.33333333, 0.33333333])

In [25]:
a = [1, 2, 3]
b = [3, 6, 9]
a + b
# [1, 2, 3, 3, 6, 9]
# np.array를 안하면 그냥 리스트로 처리된다.

[1, 2, 3, 3, 6, 9]

### dot product (백터의 내적)

In [28]:
x1 = np.array([1, 2, 3])
x1

array([1, 2, 3])

In [29]:
y1 = np.array([3, 6, 9])
y1

array([3, 6, 9])

In [30]:
np.dot(x1, y1)

42

In [34]:
x2 = np.array([180, 80, 30])
x2

array([180,  80,  30])

In [35]:
y2 = np.array([165, 60, 25])
y2

array([165,  60,  25])

In [36]:
np.dot(x2, y2)

35250

### cross product (백터의 외적)

In [37]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [38]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [39]:
np.cross(x, y)

array([-3,  6, -3])

### matrix (행렬)

In [40]:
x = np.matrix([[1, 2], [3, 4]])
x

matrix([[1, 2],
        [3, 4]])

In [41]:
x.mean()

2.5

In [44]:
x.mean(axis = 0)

matrix([[2., 3.]])

In [45]:
x.mean(axis = 1)

matrix([[1.5],
        [3.5]])

In [46]:
x.sum()

10

In [47]:
x.sum(axis = 0)

matrix([[4, 6]])

In [48]:
x.sum(axis = 1)

matrix([[3],
        [7]])

In [49]:
x = np.matrix([[1, 2], [3, 4]])

In [50]:
y = np.matrix([[3, 4], [3, 10]])

In [53]:
x.shape

(2, 2)

In [54]:
y.shape

(2, 2)

In [56]:
result = np.add(x, y)
result

matrix([[ 4,  6],
        [ 6, 14]])

In [57]:
result.shape

(2, 2)

In [59]:
result = x + y
result

matrix([[ 4,  6],
        [ 6, 14]])

In [60]:
result.shape

(2, 2)

In [61]:
x - y

matrix([[-2, -2],
        [ 0, -6]])

In [62]:
a = np.matrix([[1, 0], [0, 1]])
a

matrix([[1, 0],
        [0, 1]])

In [63]:
b = np.matrix([[1, 2]])
b

matrix([[1, 2]])

In [64]:
a.shape

(2, 2)

In [65]:
b.shape

(1, 2)

In [66]:
# np.matmul(a, b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [68]:
# transpose == T : 전치
b.shape, b.T.shape

((1, 2), (2, 1))

In [69]:
b.T

matrix([[1],
        [2]])

In [70]:
np.matmul(a, b.T)

matrix([[1],
        [2]])

In [71]:
np.dot(a, b.T)
# dot과 matmul을 거의 동일하다
# dot product로 해도 결과는 같지만 오피셜로는 matrix multiplication이 좀 더 맞다
# 그렇지만 딥러닝에선 dot을 많이 쓴다.

matrix([[1],
        [2]])

In [72]:
table = [
    [1, 1, 0, 3],
    [2, 1, 1, 4],
    [1, 0, 0, 2]
]

table = np.matrix(table)  # table을 np.matrix로 변환
table

matrix([[1, 1, 0, 3],
        [2, 1, 1, 4],
        [1, 0, 0, 2]])

In [80]:
price = [
    [2000, 3000, 2000, 500]
]

price = np.matrix(price)
price

matrix([[2000, 3000, 2000,  500]])

In [81]:
table.shape

(3, 4)

In [82]:
price.shape

(1, 4)

In [74]:
# np.matmul(table, price)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 4)

In [83]:
price.T.shape

(4, 1)

In [84]:
result = np.matmul(table, price.T)
result

matrix([[ 6500],
        [11000],
        [ 3000]])

In [85]:
result.sum()

20500

In [86]:
a = np.matrix([[1, 2], [3, 4]])
a

matrix([[1, 2],
        [3, 4]])

In [87]:
a.T

matrix([[1, 3],
        [2, 4]])

In [90]:
b = np.matrix([[1, 2], [3, 4], [5, 6]])
b

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [91]:
b.T

matrix([[1, 3, 5],
        [2, 4, 6]])

In [108]:
a = np.random.rand(1000000)

In [109]:
b = np.random.rand(1000000)

In [111]:
%%time  # 성능을 벤치마킹
s = 0

for i in range(1000000):
    s += a[i] * b[i]  # += 하면 값이 누적

s

CPU times: user 463 ms, sys: 1.88 ms, total: 465 ms
Wall time: 464 ms


249846.30412933213

In [112]:
%%time
s = np.dot(a, b)

s

CPU times: user 5.1 ms, sys: 1.21 ms, total: 6.31 ms
Wall time: 740 µs


249846.3041293315

In [113]:
m = 2000
n = 1000
p = 1

In [114]:
x = np.random.rand(m, n)
x.shape

(2000, 1000)

In [115]:
v = np.random.rand(n, p)
v.shape

(1000, 1)

In [116]:
u = np.zeros((m, p))
u.shape

(2000, 1)

In [119]:
%%time

for i in range(m):
    for j in range(n):
        u[i] += x[i][j] * v[j]

u

CPU times: user 5.44 s, sys: 3.04 ms, total: 5.44 s
Wall time: 5.44 s


array([[473.17385068],
       [475.35274145],
       [480.11279753],
       ...,
       [477.40635   ],
       [461.98783142],
       [499.78472121]])

In [120]:
%%time

u = np.dot(x, v)

u

CPU times: user 5.97 ms, sys: 1.52 ms, total: 7.48 ms
Wall time: 950 µs


array([[236.58692534],
       [237.67637073],
       [240.05639876],
       ...,
       [238.703175  ],
       [230.99391571],
       [249.8923606 ]])

In [121]:
import math

n = 1000000

In [124]:
v = np.random.rand(n)
v.shape

(1000000,)

In [122]:
u = np.zeros((n, 1))
u

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [126]:
%%time
for i in range(n):
    u[i] = math.exp(v[i])
    
u

CPU times: user 410 ms, sys: 1.82 ms, total: 411 ms
Wall time: 411 ms


array([[2.291711  ],
       [2.3972984 ],
       [1.99817014],
       ...,
       [1.15067009],
       [2.46441605],
       [1.81165038]])

In [127]:
%%time
u = np.exp(v)
u

CPU times: user 8.63 ms, sys: 2.55 ms, total: 11.2 ms
Wall time: 10 ms


array([2.291711  , 2.3972984 , 1.99817014, ..., 1.15067009, 2.46441605,
       1.81165038])

### Broadcasting

In [130]:
x = np.array([[1, 2, 3, 4]])

In [131]:
x + 10

array([[11, 12, 13, 14]])

In [134]:
x = x.T
x

array([[1],
       [2],
       [3],
       [4]])

In [135]:
x + 10

array([[11],
       [12],
       [13],
       [14]])

In [137]:
x = np.array([[1, 4], [2, 5], [3, 6]])

In [138]:
y = np.array([[10, 20, 30]])
y = y.T
y

array([[10],
       [20],
       [30]])

In [139]:
x

array([[1, 4],
       [2, 5],
       [3, 6]])

In [140]:
y

array([[10],
       [20],
       [30]])

In [141]:
x + y

array([[11, 14],
       [22, 25],
       [33, 36]])

In [142]:
x = np.array([[1, 2],[3, 4]])
x

array([[1, 2],
       [3, 4]])

In [144]:
x.mean()  # 전체평균

2.5

In [145]:
x.mean(axis = 0)  # axis = 0 : 세로 연산 (행을 의미)

array([2., 3.])

In [146]:
x.mean(axis = 1)  # axis = 1 : 가로 연산 (열을 의미)

array([1.5, 3.5])

In [147]:
x.sum(axis = 0)

array([4, 6])

In [148]:
x.sum(axis = 1)

array([3, 7])

### 예제 - 연도별 각 탐구과목 응시자 비율은?

In [149]:
data = np.matrix([[365999, 357256, 290120, 303719],
                  [245762, 246545, 243857, 264201],
                  [12580, 9362, 6273, 6625]])
data

matrix([[365999, 357256, 290120, 303719],
        [245762, 246545, 243857, 264201],
        [ 12580,   9362,   6273,   6625]])

In [153]:
num = data.sum(axis = 0)  # 연도별 전체 응시자 수
num

matrix([[624341, 613163, 540250, 574545]])

In [155]:
data / num * 100

matrix([[58.62165067, 58.26444192, 53.70106432, 52.862526  ],
        [39.3634248 , 40.20872101, 45.13780657, 45.98438765],
        [ 2.01492454,  1.52683707,  1.16112911,  1.15308636]])