In [1]:
import numpy as np

In [2]:
# 의류, 가전, 의약
# 의류 == 0, 가전 == 1, 의약 == 2
# Q1) 2 * 가전 == 의약?
# Q2) 가전 + 가전 == 의약?

In [3]:
# One Hot Encoding
# 의류(0) == [1, 0, 0]
# 가전(1) == [0, 1, 0]
# 의약(2) == [0, 0, 1]

In [18]:
y = [0, 1, 2, 1, 2]

num_class = len(np.unique(y))

y_hot = np.eye(num_class)[y]
# 이 코드를 관례로 많이 쓴다. 이 코드가 짧아서 쓰기 편하기 때문에 그냥 통채로 외우면 좋다.
y_hot

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# eye == identity matrix : 대각선으로만 1이고 나머지는 0인 matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(3)[0]

array([1., 0., 0.])

In [20]:
np.argmax(y_hot, axis = 1)  # np.argmax : 원핫인코딩 한 것을 원상복구

array([0, 1, 2, 1, 2])

In [32]:
example = [
    [0.7, 0.2, 0.1],  # 의류 가전 의약일 확률
    [0.3, 0.2, 0.5],
    [0.1, 0.1, 0.8],
    [0.2, 0.6, 0.2],
]

example = np.array(example)

example.argmax(axis = 1)  # argmax : 가장 큰 숫자가 순서상 몇번째인지 반환

array([0, 2, 2, 1])